try:
  print(x)
except:
  print("An exception occurred")
finally:
	print('Finished')